### ISSUE TITLE
Penalising False detections

### ISSUE THREAD

**Issue by tonmoyborah** [rafaelpadilla/Object-Detection-Metrics#11]
Hi @rafaelpadilla , good work here.
However, I don't think your implementation penalizes false detections of the same object like PASCAL VOC as described "However, if multiple detections of the same object are detected, it counts the first one as a positive while the rest as negatives." 
Am I missing something? Would like to know your thoughts on this.
Thank you.

**Comment by rafaelpadilla** [comment]
Dear @tonmoyborah,

Yes, this implementation does exactly what the official PASCAL VOC challange does. I highly recommend you to read the official PACAL VOC article explaining the metrics:
http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham15.pdf

The words you mentioned was taken from a very good article on medium that also explains how the Mean Average Precision metric is implemented. But in order to understand it better, you should go to the official sources.

As **written and implemented in this project**, we did what the official article says: "multiple detections of the same object in an image were considered false detections, e.g. 5 detections of a single object counted as 1 correct detection and 4 false detections". 

I also encourage you to take a look at its official Matlab implementation. There, you will see that in cases with multiple detections, the one with the highest IOU is taken. We carefully tested and compared our results with the official code.

**Comment by tonmoyborah** [comment]
I think you missed an `else` statement and you are discarding false overlapping detections and not penalizing them

**Comment by rafaelpadilla** [comment]
what do you mean by penalizing? If it is false, it just needs to be discarded.

**Comment by tonmoyborah** [comment]
In most cases we don't want our model to generate this overlapping detections, so these are considered as just other false positives and are penalized similar to other FPs.

**Comment by rafaelpadilla** [comment]
Could you please add an image to illustrate what you mean?
Also, where in the code you said it is missing an *else*? Our results were compared to the official VOC PASCAL code and our results are exactly the same.

**Comment by rafaelpadilla** [comment]
Dear @tonmoyborah,

Besides the amazing work done by the referred author, I think you still need to compare the implementations with the original VOC PASCAL done in Matlab.

You can find many implementations out there of the Precision x Recall curve that produce results that are not consistent with the the official implementation. That was the main motivation of this project: To create a project in python that obtains exactly the same results of the original code.

I encourage you to compare our results with the official implementation done in matlab and see the consistency.

Best regards

**Comment by tonmoyborah** [comment]
Yes, I totally understand. I don't have any knowledge of matlab so won't be
able to review but I believe you have done it as required. The link I
provided does it by penalising these detections which I find more apt.
However it wouldn't make much of a difference in the final score in my
opinion and also is subjective to the user. I think this issue can be
closed.
Regards
