### ISSUE TITLE
TP + FN != all ground truths ?

### ISSUE THREAD

**Issue by feiyuhuahuo** [rafaelpadilla/Object-Detection-Metrics#114]
![image](https://user-images.githubusercontent.com/32631344/87621082-98060b00-c752-11ea-841d-b77161084707.png)
In this picture, there are two TPs and one FN, but there are two ground truths. Is there anything wrong?

**Comment by feiyuhuahuo** [comment]
I reconsidered about this. For detections which match with the same ground truth, the one with the highest confidence is taken as TP, and the rest are FP. So for TP, it must satisfy three conditions: 1. The detected class is right. 2. Its IoU with a certain ground truth is higher then the threshold. 3. Among all the detections who satisfied condition1 and condition2, the one which has the highest confidence is the final TP.

**Comment by rafaelpadilla** [comment]
@feiyuhuahuo,

You are correct in your considerations. I would just simplify it in 2 conditions to avoid naming an unnecessary detection as FP:

**For each class of your dataset, do:**
1) "Its IoU with a certain ground truth is higher then the threshold."

2) "Among all the detections who satisfied condition1, the one which has the highest confidence is the final TP."

If you need more clarification on that, I recorded a video explaining the process in more details:
[https://underline.io/lecture/705-a-survey-on-performance-metrics-for-object-detection-algorithms](https://underline.io/lecture/705-a-survey-on-performance-metrics-for-object-detection-algorithms)

Please, close this issue if your doubt was clarified. Otherwise, let me know how I can help you.
