### ISSUE TITLE
Wrong meaning of (x,y,w,h) when set to BBFormat.XYX2Y2

### ISSUE THREAD

**Issue by ShenWeihan** [rafaelpadilla/Object-Detection-Metrics#118]
According to sample1.md, if format=BBFormat.XYX2Y2, the parameters **x**, **y**, **w** and h are **left**, **top**, **right** and **bottom** respectively. But it should be _left_, _bottom_, _right_ and _top_ according to lib\BoundingBox.py.

**Comment by rafaelpadilla** [comment]
@ShenWeihan,

The parameters **x**, **y**, **w** and **h** indeed (in this example) are representing **left**, **top**, **right** and **bottom**, that's why the format was specified as **XYX2Y2**.

I believe your confusion is due to the name of the variables of the BoundingBox.py, which are **x**, **y**, **w** and **h**. This is indicated [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/BoundingBox.py#L34).

I think it was clear now and will close this issue. Feel free to reopen it if you have more doubts.
