### ISSUE TITLE
Confuse on IouThreshold and IouMax ?

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [rafaelpadilla/Object-Detection-Metrics#129]
Hello Author

I read your code and i think i have a question from your code ? i hope you can expland me 

`if det[dects[d][0]][jmax] == 0:`
`   P[d] = 1  # count as true positive`
`   det[dects[d][0]][jmax] = 1  # flag as already 'seen'`
 `else:`
   `    FP[d] = 1  # count as false positive`
`

Link: https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/83a5484a0f42d6afe07f8e8f4f95a580b8f3a762/lib/Evaluator.py#L111 
line: 111 ---> 117

I saw your loop on detected and inside on groundtruth (GTBox)
i think IouMax is not Clear because when you loop each element of detected you can get a IoUmax which max more IoU before (Case: Same a image name you can get different IoU_Max). So when you if `det[dects[d][0]][jmax] == 0:` and assgin flash = 1 for it  .In the future you can get a IoU of same image name you still watch it like a False Positive Although IoUmax better than IoU Max Before 

Sorry for my english 
Thanks you for reading 
Thai Hoc

**Comment by rafaelpadilla** [comment]
@NguyenThaiHoc1 

The `iouMax` variable stores the maximum IOU between detection `d` and all groundtruths, and it is associated with `jmax`. Thus, `iouMax` and `jmax` tell us: detection `d` is best overlapped with groundtruth 'jmax' with an 'IOU=iouMax'.

Now, the judgment process happens between lines 111 and 117. If 'iouMax' is equal or lower than the threshold, detection `d` is a FP. Otherwise, it will only be a TP if no other detection was matched with the groundtruth `jmax`.

The detections are ordered by confidence. The detection with the highest confidence has higher priority in performing the match with the GTs. And each GT can only be matched with 1 detection only.

This same problem was discussed in [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/pull/112) PR. Take a look at this thread. It certainly will clarify your possible doubts.

Best regards,
Rafael
