### ISSUE TITLE
Wrong output for Edge Cases

### ISSUE THREAD

**Issue by Leon0402** [rafaelpadilla/Object-Detection-Metrics#138]
Hi, 

I think there are some checks missing in GetPascalVOCMetrics() in Evaluator.py: 

- The model predicts nothing (but there is Ground Truth data) -> TP & FP are empty arrays -> acc_FP and acc_TP as well -> recall is an empty array, but should be 0    and precision throws divided by zero error / warning and is empty as well, but should be 1 
- The model predicts a class, which is not in Ground Truth (I believe) -> npos is zero -> recall throws divided by zero warning and is empty

Not sure if I got it fully right here, but there are certainly missing some checks for some edge cases (if they really are: The model predict nothing isn't too uncommon I guess)

**Comment by rafaelpadilla** [comment]
@Leon0402 ,

Could you please provide a detection and groundtruth files, so I can replicate these behaviors?

**Comment by copiousOne** [comment]
Here is an example where 2 classes were detected and ground truth has only 1 class.  The problem is none of the groundtruth .txt files have objm in them, they are all obja or empty.  The objm in the detected result(s) is a mis-classification by the model however this edge case is not covered and the script breaks,
/lib/Evaluator.py:129: RuntimeWarning: invalid value encountered in true_divide  rec = acc_TP / npos

```
detections -> 1.txt
obja 1.000000 189 99 223 108
obja 0.999954 71 92 149 103
obja 0.978474 150 88 157 91
objm 0.541782 10 85 24 91

groundtruths 1.txt
obja 12 86 24 91
obja 151 88 157 91
obja 70 92 146 105
obja 188 100 223 108
```
