### ISSUE TITLE
COCO Detection Challenge 

### ISSUE THREAD

**Issue by alicera** [rafaelpadilla/Object-Detection-Metrics#139]
python pascalvoc.py , it is for PASCAL VOC Challenge.

How to use "COCO Detection Challenge" to evaluate.

**Comment by rafaelpadilla** [comment]
Hi @alicera 

Our new work includes all COCO metrics. Please, check the repository below:
[https://github.com/rafaelpadilla/review_object_detection_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics)

Best regards

**Comment by alicera** [comment]
1.Does the project "https://github.com/rafaelpadilla/Object-Detection-Metrics" only use voc?

2.Does the project "https://github.com/rafaelpadilla/review_object_detection_metrics" have use the method "https://github.com/rafaelpadilla/Object-Detection-Metrics#create-the-ground-truth-files" to create detection files and ground truth files ?

I only see this format for detection files and ground truth files "https://github.com/rafaelpadilla/review_object_detection_metrics#ground-truth-format"

**Comment by rafaelpadilla** [comment]
Hi @alicera,

1. Yes.
2. No, but it accepts different types of detections and groundtruth files in different formats such as COCO (json), OpenImage (csv), ImageNet (xml), text formats generated by "[https://github.com/rafaelpadilla/Object-Detection-Metrics#create-the-ground-truth-files](https://github.com/rafaelpadilla/Object-Detection-Metrics#create-the-ground-truth-files)", etc

The formats you are seeing in the link below are just for a new metric called STT (spatio-temporal tube), used for videos only. 
"[https://github.com/rafaelpadilla/review_object_detection_metrics#ground-truth-format](https://github.com/rafaelpadilla/review_object_detection_metrics#ground-truth-format)"

[This repository](https://github.com/rafaelpadilla/review_object_detection_metrics) uses [this](https://raw.githubusercontent.com/rafaelpadilla/review_object_detection_metrics/main/data/images/printshot_main_screen.png) visual interface, so you can pick the different file formats, without needing the conversions. As you can see in the interface, you can choose COCO and voc metrics.

**Comment by alicera** [comment]
Do you think the widerface validation method is the same as the PASCAL VOC Challenge method.
http://shuoyang1213.me/WIDERFACE/

Becuse I use the https://github.com/biubug6/Pytorch_Retinaface to validate widerface and the resuslt is different from the project "https://github.com/rafaelpadilla/Object-Detection-Metrics". 

For example,I only test one image. The Image grouth only have one face. I use the network to detect the image and the result have two face be detect. One of the two is incorrect.
When I compute the AP, and the AP is 1. Is it correct ?

**Comment by rafaelpadilla** [comment]
@alicera ,

I never worked with widerface, but taking a quick look at their evaluation toolkit, which is matlab, it seems an adaptation from from official PASCAL VOC toolkit. But to assure they produce the same results, I would have to debug it.

On the other hand, the [evaluation code of the Pytorch_retinaface](https://github.com/biubug6/Pytorch_Retinaface/blob/master/widerface_evaluate/evaluation.py) in the repository you mentioned, evaluates in 3 categories "Hard, Medium and Easy". The same thing here: I would have to debug the code in order to tell if they produce results equivalent to PASCAL VOC. I recommend you to debug yourself and compare the results. But first, read the README or the published paper to understand how AP is computed.

In the example you mentioned, only with the information you provided it is not possible to tell what the AP is. You would have to provide the IOU and the confidence level of each detection. But as you have only 1 groundtruth and 2 detections, your precision cannot be 1, your recall could either be 1 or 0.

Read the instructions on the README file to understand the computation of the AP better. [This](https://github.com/rafaelpadilla/review_object_detection_metrics) repository can help you to compare AP calculated with COCO and PASCAL approaches.

I hope it can guide you with your doubts.
