### ISSUE TITLE
No detection cases

### ISSUE THREAD

**Issue by saeedarabi92** [rafaelpadilla/Object-Detection-Metrics#14]
Thank you for the great repo!
How does the code count for the case the model could not detect anything?
Suppose a case that there is an image which has some objects in it. However the model could not detect anything. Should I pass an empty .txt file for that image?

**Comment by leiyaohui** [comment]
Thank you for the great repo!
Why do I run mAP with your code differently from the mAP calculated on yolo-darknet?
The difference is about 1%.

**Comment by rafaelpadilla** [comment]
Dear @saeedarabi92 ,

Yes, in the case where your image has no detections, you can just leave the . txt detection file empty. You could also have not .txt file at all. Either way will work properly :)

Regards

**Comment by rafaelpadilla** [comment]
Dear @leiyaohui,

I don't know what version of darknet you are referring to. But I had noticed that for darknet/yoloV2 their calculation for mAP was not accurate, differing from the official VOC PASCAL mAP. This is what inspired us to create our independent project. 

A while ago I had opened [an issue](https://github.com/pjreddie/darknet/issues/515) questioning darknet results. If you google a little bit, you will see that other people have also questioned their mAP implementation, specially in their google groups forum.

In order to benchmark your results, I highly recommend you to use independent projects such as ours, or official implementations like the VOC PASCAL for mAP. Otherwise your results may be biased. :) 

Regards

**Comment by rafaelpadilla** [comment]
Dear @leiyaohui,

Let me ask you something: To measure the mAP with our project, dId you use relative coordinates generated by YOLO or absolute coordinates?

**Comment by leiyaohui** [comment]
Thank you very much for your reply! I did it according to AlexeyAB/darknet, I have already changed coordinates.I use absolute coordinates.

**Comment by rafaelpadilla** [comment]
Dear @leiyaohui , 

AlexeyAB/darknet implementation has some particular points:

1) Their [default threshold is 24%](https://github.com/AlexeyAB/yolo2_light/blob/master/src/main.c#L583). Ours follows VOC PASCAL default: 50%. Check if you are using the same threshold for both cases.
2) It seems they don't evaluate objects considered [difficult](https://github.com/AlexeyAB/darknet/blob/3d2d0a7c98dbc8923d9ff705b81ff4f7940ea6ff/src/detector.c#L714). We consider all objects/detections in the txt files. If a bounding box is in the txt files, we will take it into account. If you want to omit 'difficult objects', just remove them from the text files.
3) First they load the list of objects to be evaluated, then applies detection using the weights you provided, later [NMS (Non-Maximum Suppression) is applied](https://github.com/AlexeyAB/darknet/blob/3d2d0a7c98dbc8923d9ff705b81ff4f7940ea6ff/src/detector.c#L651) with [45%](https://github.com/AlexeyAB/darknet/blob/3d2d0a7c98dbc8923d9ff705b81ff4f7940ea6ff/src/detector.c#L591), and  in the end it starts [evaluating](https://github.com/AlexeyAB/darknet/blob/3d2d0a7c98dbc8923d9ff705b81ff4f7940ea6ff/src/detector.c#L677) your detections.

Please, notice how many considerations are done before performing the evaluation. If you play with the NMS, for instance, you can reach different results.

In the scope of this project, we propose to calculate the metrics giving the user the freedom to choose their own parameters. Here the user just needs to provide us the detections. This way you can try different parameters yourself using not only YOLO, but other algorithms too. 

Best regards.
