### ISSUE TITLE
NMS ??

### ISSUE THREAD

**Issue by digitalized-hfut** [rafaelpadilla/Object-Detection-Metrics#161]
As shown in Evaluator.py, the row 114 to 120, TP is the highest class socre bbox, and other bbox are set as FP.
I think it may makes error in recall and precision.
i.e.  there is pred bbox named A=['dog', 'class score=90%', 'x', 'y', 'w', 'h', IOU=95%], 
      another pred bbox named B_1=['dog', 'class score=96%', 'x', 'y', 'w', 'h', IOU=89%]
A and B_1 are all belongs to possitive sample. 
if we set B_1 as TP, meanwhile set A as FP, this will lead error to recall and precision.
SO, should set NMS to save B_1 as one pred bbox, then compute TP FP TN FN  ??

**Comment by rafaelpadilla** [comment]
Hi @digitalized-hfut 

In this example, as you realized, if both detections (A and B_1) are provided, A will be TP and B_1 is FP. 

That's why applying NMS or any other approach to eliminate such undesired detection is a task of the object detection model. It is not a task of the evaluator.

Hope that answers your doubt.

Regards,
Rafael
