### ISSUE TITLE
Number of detected bboxes to be recorded and 11 recall level approach

### ISSUE THREAD

**Issue by eypros** [rafaelpadilla/Object-Detection-Metrics#17]
I was checking your logic and 2 questions arose:

- Since detection bboxes can be quite a lot and we usually filter to use only above a confidence threshold if that threshold (typically for me is 0.5 meaning I ignore all bboxes with confidence below this) has any impact on the mAP? Since I need to write the bbox coordinates in a txt file it make sense to filter them out but I want to know if it has any impact on mAP.

- You seem to calculate the mAP in a continuous manner rather in the proposed 11 recall levels approach. Is that so? Why do you choose this approach (I guess it's simpler to just calculate the area of the recall rectangles)? It doesn't seem to impact the resulting mAP but still it's a deviation from the original paper.

**Comment by rafaelpadilla** [comment]
Dear @eypros,

Please, find your answers below:

1) When you said "we usually filter to use only above a confidence threshold", in my understanding I assume it is done by your detection system. Thus, if you ignore them, then *yes, it may impact the mAP.* On the README of our project, note on the [illustrated example](https://github.com/rafaelpadilla/Object-Detection-Metrics#an-ilustrated-example) that the detections are ordered by their confidences, which means *they are all taken into consideration during the calculation of the mAP*. Therefore, if you discard any, they may cause an impact on the AUC. This is easily seem, for instance, if you discard detection "J".

2) You have just mentioned an excellent point :) I also believe there is no difference between calculating the 11 recall levels (the paper approach) and the AUC (as the implemented) We chose to do it this way because *that is how the official PASCAL VOC code does in Matlab.* 
The goal of our project is to provide *a set of metrics implemented exactly the same way as their official code.* 
We see a lot of independent implementations showing different mAP results. It would be easy to report your results using a tool that gives you a high mAP, right? That is what many people are doing out there.

Regards
