### ISSUE TITLE
[question] metric explained

### ISSUE THREAD

**Issue by runrunforest** [rafaelpadilla/Object-Detection-Metrics#2]
Hi Rafel, thaks for this great explaination. I just wanted to confirm if the way you explained matches the way I think it is correct.

Considering the example below, with a minimum iou of 20% and  with one ground truth object and two detections, the one with higher Iou is considered and the other is considered as a FP. When we rank the detecitons by confidence, we get:

|       | Confidence | AccTP | AccFP | Precision | Recall |
|-------|------------|-------|-------|-----------|--------|
| Green | .99        | 0     | 1     | 0         | 0      |
| Blue  | .30        | 1     | 1     | 0.5       | 1      |

The first row does not make sense to me at all because we are thresholding our detection by the one with top confidence and neglecting all the other detections and thus, there is no reason to consider the green one as a FP. It was considered as FP because there was another detection with higher Iou. Does it make sense to you?

![avgprecision](https://user-images.githubusercontent.com/34770090/42654832-5f4b429e-85f0-11e8-8863-a18142fbdaa6.jpg)

**Comment by rafaelpadilla** [comment]
Dear @runrunforest ,

Yes. I think you got it right: If two or more detections overlap the same ground truth object, the PASCAL VOC metric considers only the detection with the greatest IoU and **discards the others**. By discarding the others, we are considering them as a FP.

In your example, the blue and green detections overlap the same object, but the blue detection has greater IoU (40%), therefore it is a TP and the **green detection is FP**.

Your table values are right. The value "accumulated TP" for the green box is 0 and it is correct, because **the green detection is FP**. Therefore, the "accumulated FP" for the green box must be 1. As you said: "It was considered as FP because there was another detection with higher Iou". The goal is not only to detect high confidence objects, but also evaluate how well the objects were detected by looking at its IoU. The green box has a higher confidence, but it detected a smaller area of the object. **There is a trade-off between the precision and recall of the detections that the AP curve shows us.** As I mentioned: **A poor object detector needs to increase the number of detected objects (increasing False Positives = lower precision) in order to retrieve all ground truth objects (high recall).** It will start making more sense to you if you have a larger number of detections with a wider range of confidence values. 

In my post I demonstrated the example using the table, because we are interested in plotting the **interpolated precision** and by taking a look at the table (from the bottom up) is a good way to visualize the maximum precision at a given recall level.

Hope it makes sense to you.

Regards,
Rafael

**Comment by runrunforest** [comment]
Yep, now it makes sense to me.

Thanks a lot.

**Comment by LarsNeR** [comment]
Hi @rafaelpadilla I have one question about your answer. You are saying:

> If two or more detections overlap the same ground truth object, the PASCAL VOC metric considers only the detection with the greatest IoU and discards the others

Do you have a source where they describe that? In the papers ([The PASCAL Visual Object Classes (VOC) Challenge](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.5766&rep=rep1&type=pdf) and [The PASCAL Visual Object Classes Challenge: A Retrospective](http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham15.pdf) ) I only find this:
> Detections output by a method were assigned to ground truth objects satisfying the overlap criterion in order **ranked by the (decreasing) confidence** output.

For me this looks like they are ordering by confidence and not by IoU. Or is that something different?

Thanks for your help and the great repo!
