### ISSUE TITLE
Question:use the parameter about -gtcoords and -detcoords

### ISSUE THREAD

**Issue by luzhibo** [rafaelpadilla/Object-Detection-Metrics#24]
Dear @rafaelpadilla ,
I am using your code to run yolov3 model,in your instructions ,about the -gtcoords and -detcoords,you say I should use '-gtcoords rel' in yolo model.Because the coordinates are relative to the image sizecoordinates are relative to the image size.
But when I use default sets,the code run success.I think it is not necessary because my ground truth bounding boxes infomations'format is same as detected bounding boxes information'format.
Can you give me some explanation?
Thanks.

**Comment by rafaelpadilla** [comment]
Dear @luzhibo,

Sorry, I think I did not understand your doubt.

If the coordinates of your detections are already in absolute values, you don't need to use the argument **--detformat**, because its default value takes absolute coordinates (X Y width height) for your bounding boxes.

Regards

**Comment by luzhibo** [comment]
Dear @rafaelpadilla ,
Thanks for your replying.

I use the code to assess yolo3 model' ap and map.In my txt files,the ground truth bounding boxes and detected boxes are (left,top,right,bottom),these coordinates already  relate to upper left corner of image ,so this is the absolute coordinates and i should use the default value.
Is my understanding right? 
Thanks

**Comment by rafaelpadilla** [comment]
@luzhibo,

In your case, regarding the detections only, you should use the arguments:

**-detformat xyrb**
and
**-detcoords abs** (optional, because the default value is already **abs**)

Besides, you must use the others arguments:
**-gtcoords:** the groundtruth coordinates
**-gtformat:** the goundtruth format (**abs** or **rel**)
**-threshold:** the IOU threshold 
**--gtfolder:** folder with your groundtruth files
**--detfolder:** folder for your detection files
