### ISSUE TITLE
why should  order the detections by their confidences

### ISSUE THREAD

**Issue by hust-kevin** [rafaelpadilla/Object-Detection-Metrics#27]
![image](https://user-images.githubusercontent.com/23699630/48929487-4a58e100-ef24-11e8-8fcd-ca9b69bf6068.png)

**Comment by hust-kevin** [comment]
I kown the reason,but I have another question.
when  I read the code of [ssd](https://github.com/amdegroot/ssd.pytorch/blob/master/eval.py#L338),if  there are more than one detection overlapping a ground truth,for example three, and all of  three bbox's iou larger than a threshold,then pick the bbox has highest confidence rather than the highest iou

**Comment by sagartesla** [comment]
@hust-kevin Can you help me understand Why should order the detentions by their confidences ?
And Why do not we calculate P-R curve by varying classifier threshold from 0 to 1 with interval of 0.01 (some step), and Calculate P and R value at that threshold . Then Plot all the P-R Values ?

**Comment by rafaelpadilla** [comment]
Dear @hust-kevin,

I cannot answer on behalf of someone else's repository. But **according to PASCAL VOC metrics, when you have multiple detections of the same object you should consider the one with the highest IOU**.

Regards,
Rafael

**Comment by rafaelpadilla** [comment]
Dear @sagartesla,

The official PASCAL VOC [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.5766&rep=rep1&type=pdf) says:

"Detections output by a method were assigned to ground truth objects satisfying the overlap criterion in order **ranked by the (decreasing) confidence output**"

The classifier threshold (IOU) is fixed for the PASCAL VOC. On other competitions, such as [COCO](http://cocodataset.org/#detection-eval), it is possible to test on different IOU thresholds.

Please, close this issue if your question regarding this issue was answered properly.

Regards,
Rafael

**Comment by dongzhuoyao** [comment]
@sagartesla 2nd question:  I think "calculate P-R curve by varying classifier threshold from 0 to 1 with interval of 0.01 (some step)" will obtain the same result as the official method. However, the official method is faster(less iteration, only calculate at truly boundary point.). 

For example, just imagine you iteration the classifier threshold between (91%, 94%) in the Sample 2, 
the precision, recall both keep unmoved.
