### ISSUE TITLE
Using this approch on segmented images rather than bounding boxes.

### ISSUE THREAD

**Issue by Gasethata** [rafaelpadilla/Object-Detection-Metrics#3]
Hey there, your implementation is nice and would provide a detailed performance evaluation. I want to use this to evaluate my results for moving objects detection in a video....but im using background subtraction which gives an output of the moving object segmented...
Refer to the image below for simple understanding....
.......ORIGINAL IMAGE.......DETECTION.......GROUND-TRUTH

![exam](https://user-images.githubusercontent.com/28896486/42884450-a76084f6-8a9e-11e8-9300-6b9acce94cd5.png)

So in this case how can I use the approach, since im not using bounding boxes
Thank you in advance!

**Comment by rafaelpadilla** [comment]
Dear @Gasethata ,

The approach you want to use is not the purpose of this repository. Here I developed metrics for object detections for different classes using bounding boxes.

It seems to me that your evaluation method is pixel-wise instead of using bounding boxes. **You should try to look for metrics that are applied to semantic segmentation approach, and for the most popular metrics used in your particular case.** But if you still want to use bounding boxes to evaluate the detected classes' regions, you can adapt my code to obtain bounding boxes of the pixel regions. If you do it for ground truth and detected images, you can use my code to obtain mAP. But again, I don't know if this is suited to your case.

Regards.
