### ISSUE TITLE
how to calculate recall in the table?

### ISSUE THREAD

**Issue by smartparrot** [rafaelpadilla/Object-Detection-Metrics#32]
Hi, sir, I know how to calculate the precision in the table, but I can't figure out how to calculate the recall in the second table. recall need FN, how to get FN

**Comment by rafaelpadilla** [comment]
Dear @smartparrot,

The Recall is given by:

TP/(TP+FN) = TP/(all ground truths)

In the second table the TP used is the ACC TP (accumulated True Positive) and "all ground truths" is 15, (the total number of ground truths in the example).

Regards

**Comment by smartparrot** [comment]
Thanks, now I know how to calculate the precision and recall, but why the denominator of precision formula is accumulated detections , while denominator of recall is all the number of ground truth samples in the table?

**Comment by rafaelpadilla** [comment]
Dear @smartparrot,

The table is just a way to visualize how the detector behaves in different levels of confidence. 

Considering the example presented in the README: if we consider a TP only the detections with confidence $\geq$ 95%, our model would only be able to detect the object represented by the box R. Therefore: TP = 1, all ground truths that the model should have detected = 15, all detections = 1 (because this was the only detection we have so far).

Now, let's be less strict and consider lower confidence values. Only detections with confidence $\geq$ 88% will be considered. In this case we would have detected the objects represented by the boxes R, Y, J and A.  But the boxes A and Y are FP, once their IOU is below our pre-defined threshold (30%). Therefore: TP = 2, FP = 2, all detections = 4, all ground truths = 15. It results in Precision = 2/4 = 1/2 and Recall = 2/15 = 0,13333.

Follow this explanation with the values shown in the example presented in the README. I hope you understand it.

Regards

**Comment by smartparrot** [comment]
Your explanation is very clear, thanks very much.
