### ISSUE TITLE
Questions. 

### ISSUE THREAD

**Issue by VinayakaPrabhu** [rafaelpadilla/Object-Detection-Metrics#36]
Hello @rafaelpadilla 
Thank you for all your support. This repo is extremely helpful.

I have few questions. Could you please help me.
I have 1 class and  used tinyYolo.
Q1 ) How should we know which threshold is best to choose?
at 0.1 Threshold I got mAP : 63.07% , lamr : 0.52  , FP : 3942 and TP 1460.
at 0.3 Threshold         mAP : 59.72% , lamr : 0.52  , FP  : 861  and TP 1325.
at 0.5 Threshold         mAP : 52.24% , lamr : 0.57  , FP  : 861 and TP 1121

So. Is there a way to find an optimal threshold at one go? 

Q2.) What is the difference between lamr and ROC? (I am not clear with both terms)

Q3 ) Is there any difference between IOUThreshold and threshold?If so could you please explain. 

Sorry. If the question look dumb or illogical. I am new to the topic

Thank you for your time.

**Comment by rafaelpadilla** [comment]
Dear @VinayakaPrabhu,

Answering your questions:

1) It is hard do say which threshold is the best when evaluating mAP. It depends on how many classes you have and their particular AP. The number of TP and FP can help, but it is a trade-off between how many wrong detections you allow to have in order to obtain the TP. In a real system you should evaluate how critical your results will be if you increase the amount of FP detections.

2) I don't know Iamr. Do you have a paper or a reference to it? Have you googled it?

3) IOUthreshold is the threshold that will define if your detection is a TP or a FP considering the area of intersection with the object (it is explained in the README). If your IOU threshold is very strict (high values) your bounding boxes must be very close to the ground truth ones. If your threshold is very low, you are accepting a relative small area of intersection between your detection and the object (bad detections). Usually the IOUThreshold is set to 50% to 75%. But it all depends on the purpose of your application.
The term "threshold" itself is usually applied to the confidence of the detections. Usually object detectors retrieve  bounding boxes, classes and the confidence values. The confidence value means how confident the detector is about the class of the object.

I hope it helped.

**Comment by VinayakaPrabhu** [comment]
Thanks a lot.

is there any way to plot these two curves in the result?

![visdom](https://user-images.githubusercontent.com/19304902/54010282-2c8e4f80-4194-11e9-9ba8-8f61ad00734a.png)

Or anything like this? So. That a best threshold or best mAP etc can be extracted?

**Comment by rafaelpadilla** [comment]
Dear @VinayakaPrabhu,

Those curves are usually used to evaluate models used for classification. This is not the goal of our repository. Here we use a different metric for **object detection** only.

Regards,
Rafael
