### ISSUE TITLE
How should be prepared data if file with prediction bbox  or ground truth box is empty?

### ISSUE THREAD

**Issue by JamesHames** [rafaelpadilla/Object-Detection-Metrics#40]
How should be prepared data if prediction file or ground truth file is empty?

**Comment by rafaelpadilla** [comment]
Dear @JamesHames,

Let me see if I understood your doubt: You have images that have no detections and/or no ground truth bounding boxes? If this is your question, you should leave the files empty, simple as that.

Regards,
Rafael

**Comment by Kirayue** [comment]
Hi, @rafaelpadilla, I think I have a similar question. 
I am trying to combine `lib` to my own project to calculate mAP. I followed Sample 2, and try to add bbox to `BoundingBoxes`, what if there is an image with no ground truth (e,g, only background), but the model has predictions on it. There is no doubt that we add a detection bbox to `BoundingBoxes` instance, but how about the ground_truth? Should I create a bbox instance with xywh all equal to 0 and add to `BoundingBoxes` instance, or just ignore it because on ground truth on it (i.e. there is a filename only has detection bbox but no ground truth bbox in `BoundingBoxes`)

**Comment by HamsterHuey** [comment]
@Kirayue - From looking at the code, I believe you do not need to insert any `BoundingBox` object for the ground-truth if the image is a background only image with no actual ground-truth objects in them. The way the code is structured, any detection for such a "background" image will not be matched to a corresponding ground-truth, and as a result, will correctly be assigned as a false positive.
