### ISSUE TITLE
How confidence is used

### ISSUE THREAD

**Issue by Jnkmura** [rafaelpadilla/Object-Detection-Metrics#56]
Hello, I've read some other closed issues but still I don't understand how confidence works in this context.

For instance, for one image my model predicts 3 outputs:
A: confidence 0.9
B: confidence 0.7
C: confidence 0.2

Should I use all of them? Even if confidence for C is low or I should filter them before (like using a threshold of 0.5?).
I was hoping to find what is the best threshold of confidence that I should use with my model.
Thanks.

**Comment by rafaelpadilla** [comment]
Dear @Jnkmura ,

It depends on how robust your detector is. By thresholding your confidence, you may be missing correct detections or including wrong detections in your final output.

**You should not consider the confidence only. You also need to consider the IOU**. That's why the mAP is a good way to evaluate the robustness of your detector in different levels of confidences.

A straight answer to you is: plot the AP curve for each of your classes and choose the best point that gives you the desired relation between precision and recall.

**Comment by Jnkmura** [comment]
Yes, you are right, thats why I wanted to check the mAP values over all possible confidence thresholds.
Thank you for your answer!
