### ISSUE TITLE
Understanding the graph

### ISSUE THREAD

**Issue by hafizulislamhimel45** [rafaelpadilla/Object-Detection-Metrics#6]
I've trained a model and generated result using your Object-Detection-Metrics repository. 
For threshold value 0.3 
![38264099_10217572824499431_1698056367476047872_n](https://user-images.githubusercontent.com/28942122/43661035-8bdba076-9782-11e8-888c-9e0ecf45fb27.png)
For threshold value 0.5
![38284421_10217572824579433_4509303524328210432_n](https://user-images.githubusercontent.com/28942122/43661053-9f895c58-9782-11e8-9999-5479c5abfb15.png)

I am really having a hard time understanding the graph. Can you please explain the graph that will help me a lot. If you can manage time please reply.

**Comment by rafaelpadilla** [comment]
Dear @hafizulislamhimel45,

The [tutorial](https://github.com/rafaelpadilla/Object-Detection-Metrics) explains the creation and the interpretation of the Average x Precision graph:
An object detector of a particular class is considered good if its precision stays high as recall increases, which means that if you vary the confidence threshold, the precision and recall will still be high. Another way to identify a good object detector is to look for a detector that can identify only relevant objects (0 False Positives = high precision), finding all ground truth objects (0 False Negatives = high recall).

If my eyes are not fooling me because of the scale of your graphs, I could say:
Comparing both of your plots, the one with threshold 0.3 performed better than the 0.5 one for all recall values. The 0.3 obtained an AP=88.33% while the 0.5 had 80.88%. For shorter recall values (from 0 to 0.4) the 0.3 plot got very high precision, reaching values very close to 1. And only when recall values got higher than 0.4, the precision started decreasing.

It means that:
The 0.3 curve shows that your detector was able to detect correctly up to 40% of all relevant ground truths with a very high precision. In other words, we can say that it detected 40% of the ground truth very efficiently, without having any FP. But in order to to detect more than 40% of the ground truths, this detector starts making mistakes and detecting things it shouldn't (FP). That's why the precision decreases.
The 0.5 curve was not that efficient. It always detected some FP, because the 100% precision was never reached.

I hope it helped.
