### ISSUE TITLE
Sort on Confidence or IoU for multiple detections

### ISSUE THREAD

**Issue by johanek2** [rafaelpadilla/Object-Detection-Metrics#78]
You write:
> In some images there are more than one detection overlapping a ground truth (Images 2, 3, 4, 5, 6 and 7). For those cases the detection with the highest IOU is considered TP and the others are considered FP. This rule is applied by the PASCAL VOC 2012 metric: "e.g. 5 detections (TP) of a single object is counted as 1 correct detection and 4 false detections”.

But in the VOC paper they say:
> Detections output by a method were assigned to groundtruth objects satisfying the overlap criterion in order rankedby the (decreasing) confidence output. Multiple detectionsof the same object in an image were considered false detec-tions e.g. 5 detections of a single object counted as 1 correctdetection and 4 false detection

I.e. they say they sort on confidence but you say you sort on IoU, is this an error or am I missing something?

**Comment by stratomaster31** [comment]
I think both statements are not contradictory. The first one says that for multiple detections of the same object, the one with highest IoU is selected as TP. Then, for computing the prec-rec curve, you sort the predictions by decreasing score....

Example (5 bboxes for the same gt object):

```
| IoU  | Score | TP | FP | Precision |
|------|-------|----|----|-----------|
| 0.7  | 0.92  | 0  | 1  | 0         |
| 0.9  | 0.91  | 1  | 0  | 0.5       |
| 0.45 | 0.88  | 0  | 1  | 0.333333  |
| 0.65 | 0.81  | 0  | 1  | 0.25      |
| 0.77 | 0.79  | 0  | 1  | 0.2       |
```

**Comment by rafaelpadilla** [comment]
Hi @johanek2,

Thank you for your comment.

The detections are sorted by confidence, not by their IOUs. I think you mixed the things up a little. I can't find where it is written that we should sort by the IOU.

To be clear, please, take a look at this [example](https://github.com/rafaelpadilla/Object-Detection-Metrics#an-ilustrated-example). Looking at image 3 you will notice that there are 3 detections for the same object: G, H and I with confidences 18%, 67% and 38% respectively.

For cases where there are multiple detections for the same groundtruth, **VOC Pascal considers the detection with the highest IOU as TP and the others as FP**. Visually we can see that the detection G has the highest IOU with the groundtruth (sorry for not adding in this example the IOU values for the detections). That's why the bounding box G is assigned as TP and H and I are FP.

Later on, on the second table, **the detections are ordered by confidence**, as stated by VOC Pascal.   This is necessary to calculate the Precision and Recall for each detection.

I hope I was able to answer your question.

Best regards

**Comment by depthwise** [comment]
Here's what I don't understand. If I, say, replace Python's (stable) sort with `np.argsort`, and then rearrange the boxes based on that, I get a different result. Seems like the algorithm implemented here depends on the order in which the boxes come into it, which doesn't seem right.

I.e. I just modify:
```python3
dects = sorted(dects, key=lambda conf: conf[2], reverse=True)
```

And replace it with
```python3
confidences = [d[2] for d in dects]
idxs = np.argsort(-np.array(confidences))
dects = [dects[i] for i in idxs
```
which is roughly how this is implemented in Faster-RCNN, I get a different result using the default data in the repo.

**Comment by depthwise** [comment]
Furthermore, if I specify `kind = "stable"` for the argsort, I get the same result again.

**Comment by johanek2** [comment]
@depthwise se my other issue https://github.com/rafaelpadilla/Object-Detection-Metrics/issues/77

**Comment by rafaelpadilla** [comment]
Dear @stratomaster31 @depthwise @johanek2 @zhenglilei,

I was reviewing the README, and noticed the miss explanation of the criterion used when 2 or more detections overlap the same groundtruth. You are right @johanek2, we consider the first one as TP. So, the one as the highest IOU is considered. 

Sorry for the miss understanding. And thank you for your comment.
