### ISSUE TITLE
ROC curve

### ISSUE THREAD

**Issue by SiwarBG-2019** [rafaelpadilla/Object-Detection-Metrics#85]
How to compute all negatives in order to plot ROC curve please?

**Comment by rafaelpadilla** [comment]
@SiwarBG-2019 ,

ROC curve does not apply in this approach.

For the ROC curve you would need False Positive Rate (FPR) and True Positive Rate (TPR). Seen that, for the FPR you would need the True Negatives (TN):

FPR = FP / (FP+TN)

As mention [here](https://github.com/rafaelpadilla/Object-Detection-Metrics#true-positive-false-positive-false-negative-and-true-negative), note that we cannot calculate TN in our approach.

That's why we use the AUC of the Precision x Recall curve instead of the ROC.

**Comment by SiwarBG-2019** [comment]
Thanks a lot for your help.
