### ISSUE TITLE
/content/Object-Detection-Metrics-master/lib/Evaluator.py:126: RuntimeWarning: invalid value encountered in true_divide   rec = acc_TP / npos

### ISSUE THREAD

**Issue by umairjavaid** [rafaelpadilla/Object-Detection-Metrics#91]
I'm getting the following warning: 
```
/content/Object-Detection-Metrics-master/lib/Evaluator.py:126: RuntimeWarning: invalid value encountered in true_divide
  rec = acc_TP / npos
```
and then the code keeps on running in an endless loop

**Comment by rafaelpadilla** [comment]
@umairjavaid ,

Could you please provide your detection and groundtruth files? I will investigate the problem.

**Comment by umairjavaid** [comment]
I mistakenly provided wrong detected class name in the detection files - that were not present in the ground-truth files. That caused the program to run in an endless loop.
kindly, do a check if the detected class name is present in the groundcloth files before the program evaluates.

**Comment by rafaelpadilla** [comment]
@umairjavaid ,

We will provide this check in the next version. Thank you for the feedback!

**Comment by khachuy1508** [comment]
I have a same problem, how can i fix it???
I have only 3 class in my model

**Comment by rafaelpadilla** [comment]
@khachuy1508 ,

You have to check if all 3 classes in your detections are presented in the groundtruths.

**Comment by rafaelpadilla** [comment]
> @khachuy1508 ,
> 
> You have to check if all 3 classes in your detections are presented in the groundtruths.

@khachuy1508 @umairjavaid 
We had been working on a new project that accepts bounding boxes in different file formats and evaluates detections with COCO and PASCAL metrics. That's why we had not applied the requested changes yet. But these modifications were applied in the new project that can be seen in the link below:
[https://github.com/rafaelpadilla/review_object_detection_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics)
